### ISSUE TITLE
Feature Request: RANDOMFROMQUERY

### ISSUE THREAD

**Issue by brandon-toner** [RoamJS/smartblocks#113]
Idea: Like RANDOMBLOCKMENTION, but for a more specific query. 

Why I want this: 
- To return "random idea (#I) related to {area}", or "random question (#Q) related to {area}"

I'm also interested if you know of another way to accomplish the same result. 

Thanks!

**Comment by dvargas92495** [comment]
With Query Builder extension, you could define a query and specify random settings.

The `<%QUERYBUILDER%>` command then returns whatever is configured, but I sense once you have it set up on Query Builder itself, it will be sufficient.

**Comment by brandon-toner** [comment]
Great — I'll check that out!

**Comment by brandon-toner** [comment]
OK I figured out the query logic... could I use the Smartblock command to trigger the random output on this query and place the block reference when the command was triggered? 

Desired workflow:
- Place cursor on DNP
- "jj Random Pharmacy Idea" to trigger SB Workflow
- *random query result is block referenced on the page*

![2024-01-20-0017 11_Screenshot](https://github.com/RoamJS/smartblocks/assets/67168828/9e629504-e190-4b66-8094-d877f6e578a2)

**Comment by dvargas92495** [comment]
yea, if you give this query builder instance an alias on the top right (e.g. `Pharmacies`), then you should be able to do:

`<%QUERYBUILDER:Pharmacies%>`

**Comment by brandon-toner** [comment]
Wowwwww. Ok awesome! This is great.
