### ISSUE TITLE
[Bug] Input hot keys don't work properly if you type quickly 

### ISSUE THREAD

**Issue by msf999** [RoamJS/smartblocks#73]
If you have an input hot key and use it at the end of a sentence that you typed quickly then the whole sentence goes away and is replaced with the hot key. However, if you wait at the end of the sentence for a second or two before typing the hot key then it works as expected. I can provide a video/gif in case my description is not clear.

Thanks!

**Comment by dvargas92495** [comment]
Could you please provide a video? Description seems clear but the video will help highlight other behaviors that could be affecting the timing

**Comment by msf999** [comment]
Thanks for the quick response David. Here's a quick gif:
https://gifyu.com/image/SdwzO
The hotkey anki is assigned to the smartblock shown in the gif. Let me know if it is not clear.

**Comment by dvargas92495** [comment]
![Screen Shot 2023-04-07 at 10 10 35 AM](https://user-images.githubusercontent.com/7143571/230623094-abd0a005-80de-4dcf-ba51-a6a154c96520.png)

page is not loading. But also we just merged in another fix related to hot key issues that's under review by Roam Depot. Once that update goes live, let's wait and see if this issue gets addressed

**Comment by msf999** [comment]
Sorry about that, the website works for me. Here's the gif:
![chrome-capture-2023-3-7](https://user-images.githubusercontent.com/59384781/230685526-f6992770-c3af-42b8-bbb9-d96d981990cf.gif)

I will let you know if it is fixed once the new update is live on Roam Depot. Thanks.

**Comment by dvargas92495** [comment]
Ah I understand now - yea Idt the latest update will affect this. Added it to our backlog
